[2021-02-19 16:22:28,210] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-02-19T13:22:25.563543+00:00 [queued]>
[2021-02-19 16:22:28,231] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-02-19T13:22:25.563543+00:00 [queued]>
[2021-02-19 16:22:28,231] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-19 16:22:28,231] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-02-19 16:22:28,231] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-19 16:22:28,245] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): pivot_dataset> on 2021-02-19T13:22:25.563543+00:00
[2021-02-19 16:22:28,248] {standard_task_runner.py:52} INFO - Started process 79622 to run task
[2021-02-19 16:22:28,250] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'titanic_pivot', 'pivot_dataset', '2021-02-19T13:22:25.563543+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/titanicTest.py', '--cfg-path', '/tmp/tmptncis_fy', '--error-file', '/tmp/tmp09m5ndan']
[2021-02-19 16:22:28,250] {standard_task_runner.py:77} INFO - Job 10: Subtask pivot_dataset
[2021-02-19 16:22:28,288] {logging_mixin.py:104} INFO - Running <TaskInstance: titanic_pivot.pivot_dataset 2021-02-19T13:22:25.563543+00:00 [running]> on host oleg-desktop
[2021-02-19 16:22:28,329] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=titanic_pivot
AIRFLOW_CTX_TASK_ID=pivot_dataset
AIRFLOW_CTX_EXECUTION_DATE=2021-02-19T13:22:25.563543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-19T13:22:25.563543+00:00
[2021-02-19 16:22:29,356] {python.py:118} INFO - Done. Returned value was: None
[2021-02-19 16:22:29,403] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=titanic_pivot, task_id=pivot_dataset, execution_date=20210219T132225, start_date=20210219T132228, end_date=20210219T132229
[2021-02-19 16:22:29,436] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-02-19 16:22:29,463] {local_task_job.py:146} INFO - Task exited with return code 0
