[2021-02-19 14:39:45,731] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-02-19T11:39:42.975956+00:00 [queued]>
[2021-02-19 14:39:45,753] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-02-19T11:39:42.975956+00:00 [queued]>
[2021-02-19 14:39:45,753] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-19 14:39:45,753] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-02-19 14:39:45,753] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-19 14:39:45,767] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): pivot_dataset> on 2021-02-19T11:39:42.975956+00:00
[2021-02-19 14:39:45,769] {standard_task_runner.py:52} INFO - Started process 58186 to run task
[2021-02-19 14:39:45,772] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'titanic_pivot', 'pivot_dataset', '2021-02-19T11:39:42.975956+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/titanicTest.py', '--cfg-path', '/tmp/tmp3htq02jo', '--error-file', '/tmp/tmp7bb_pjv_']
[2021-02-19 14:39:45,772] {standard_task_runner.py:77} INFO - Job 8: Subtask pivot_dataset
[2021-02-19 14:39:45,819] {logging_mixin.py:104} INFO - Running <TaskInstance: titanic_pivot.pivot_dataset 2021-02-19T11:39:42.975956+00:00 [running]> on host oleg-desktop
[2021-02-19 14:39:45,867] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=titanic_pivot
AIRFLOW_CTX_TASK_ID=pivot_dataset
AIRFLOW_CTX_EXECUTION_DATE=2021-02-19T11:39:42.975956+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-19T11:39:42.975956+00:00
[2021-02-19 14:39:46,868] {python.py:118} INFO - Done. Returned value was: None
[2021-02-19 14:39:46,908] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=titanic_pivot, task_id=pivot_dataset, execution_date=20210219T113942, start_date=20210219T113945, end_date=20210219T113946
[2021-02-19 14:39:46,941] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-02-19 14:39:46,985] {local_task_job.py:146} INFO - Task exited with return code 0
