[2021-03-03 13:12:41,693] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-03-03T10:12:38.037034+00:00 [queued]>
[2021-03-03 13:12:41,702] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-03-03T10:12:38.037034+00:00 [queued]>
[2021-03-03 13:12:41,702] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 13:12:41,702] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-03-03 13:12:41,702] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 13:12:41,719] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): pivot_dataset> on 2021-03-03T10:12:38.037034+00:00
[2021-03-03 13:12:41,721] {standard_task_runner.py:52} INFO - Started process 35753 to run task
[2021-03-03 13:12:41,725] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'titanic_pivot', 'pivot_dataset', '2021-03-03T10:12:38.037034+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/titanicTest.py', '--cfg-path', '/tmp/tmpb9dicytd', '--error-file', '/tmp/tmp8nom3n81']
[2021-03-03 13:12:41,725] {standard_task_runner.py:77} INFO - Job 26: Subtask pivot_dataset
[2021-03-03 13:12:41,761] {logging_mixin.py:104} INFO - Running <TaskInstance: titanic_pivot.pivot_dataset 2021-03-03T10:12:38.037034+00:00 [running]> on host oleg-desktop
[2021-03-03 13:12:41,802] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=titanic_pivot
AIRFLOW_CTX_TASK_ID=pivot_dataset
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T10:12:38.037034+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T10:12:38.037034+00:00
[2021-03-03 13:12:42,794] {python.py:118} INFO - Done. Returned value was: None
[2021-03-03 13:12:42,844] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=titanic_pivot, task_id=pivot_dataset, execution_date=20210303T101238, start_date=20210303T101241, end_date=20210303T101242
[2021-03-03 13:12:42,877] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-03 13:12:42,897] {local_task_job.py:146} INFO - Task exited with return code 0
