[2021-02-19 14:38:35,081] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-02-19T11:38:33.012393+00:00 [queued]>
[2021-02-19 14:38:35,103] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-02-19T11:38:33.012393+00:00 [queued]>
[2021-02-19 14:38:35,103] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-19 14:38:35,103] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-02-19 14:38:35,103] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-19 14:38:35,110] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): pivot_dataset> on 2021-02-19T11:38:33.012393+00:00
[2021-02-19 14:38:35,112] {standard_task_runner.py:52} INFO - Started process 57847 to run task
[2021-02-19 14:38:35,115] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'titanic_pivot', 'pivot_dataset', '2021-02-19T11:38:33.012393+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/titanicTest.py', '--cfg-path', '/tmp/tmpof5h680m', '--error-file', '/tmp/tmp27volfcy']
[2021-02-19 14:38:35,115] {standard_task_runner.py:77} INFO - Job 6: Subtask pivot_dataset
[2021-02-19 14:38:35,151] {logging_mixin.py:104} INFO - Running <TaskInstance: titanic_pivot.pivot_dataset 2021-02-19T11:38:33.012393+00:00 [running]> on host oleg-desktop
[2021-02-19 14:38:35,243] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=titanic_pivot
AIRFLOW_CTX_TASK_ID=pivot_dataset
AIRFLOW_CTX_EXECUTION_DATE=2021-02-19T11:38:33.012393+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-19T11:38:33.012393+00:00
[2021-02-19 14:38:36,231] {python.py:118} INFO - Done. Returned value was: None
[2021-02-19 14:38:36,260] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=titanic_pivot, task_id=pivot_dataset, execution_date=20210219T113833, start_date=20210219T113835, end_date=20210219T113836
[2021-02-19 14:38:36,293] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-02-19 14:38:36,327] {local_task_job.py:146} INFO - Task exited with return code 0
