[2021-03-03 14:23:42,952] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-03-03T11:23:38.590752+00:00 [queued]>
[2021-03-03 14:23:42,982] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: titanic_pivot.pivot_dataset 2021-03-03T11:23:38.590752+00:00 [queued]>
[2021-03-03 14:23:42,982] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 14:23:42,982] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-03-03 14:23:42,982] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 14:23:42,998] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): pivot_dataset> on 2021-03-03T11:23:38.590752+00:00
[2021-03-03 14:23:43,000] {standard_task_runner.py:52} INFO - Started process 49775 to run task
[2021-03-03 14:23:43,004] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'titanic_pivot', 'pivot_dataset', '2021-03-03T11:23:38.590752+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/titanicTest.py', '--cfg-path', '/tmp/tmpdra_9wej', '--error-file', '/tmp/tmpav4dqkyk']
[2021-03-03 14:23:43,004] {standard_task_runner.py:77} INFO - Job 5: Subtask pivot_dataset
[2021-03-03 14:23:43,047] {logging_mixin.py:104} INFO - Running <TaskInstance: titanic_pivot.pivot_dataset 2021-03-03T11:23:38.590752+00:00 [running]> on host oleg-desktop
[2021-03-03 14:23:43,097] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=titanic_pivot
AIRFLOW_CTX_TASK_ID=pivot_dataset
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T11:23:38.590752+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T11:23:38.590752+00:00
[2021-03-03 14:23:44,086] {python.py:118} INFO - Done. Returned value was: None
[2021-03-03 14:23:44,106] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=titanic_pivot, task_id=pivot_dataset, execution_date=20210303T112338, start_date=20210303T112342, end_date=20210303T112344
[2021-03-03 14:23:44,164] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-03 14:23:44,176] {local_task_job.py:146} INFO - Task exited with return code 0
